import { defineField, defineType } from "sanity";

const ctaFields = [
  defineField({ name: "label", title: "Label", type: "string" }),
  defineField({ name: "href", title: "Link", type: "string" }),
] as const;

const titleDescriptionFields = [
  defineField({ name: "title", title: "Title", type: "string" }),
  defineField({ name: "description", title: "Description", type: "text", rows: 3 }),
] as const;

export const homePage = defineType({
  name: "homePage",
  title: "Home Page",
  type: "document",
  fields: [
    defineField({ name: "heroLabel", title: "Hero Label", type: "string" }),
    defineField({ name: "heroTitle", title: "Hero Title", type: "string" }),
    defineField({ name: "heroSubtitle", title: "Hero Subtitle", type: "text", rows: 3 }),
    defineField({ name: "heroPrimaryCta", title: "Hero Primary CTA", type: "object", fields: [...ctaFields] }),
    defineField({ name: "heroSecondaryCta", title: "Hero Secondary CTA", type: "object", fields: [...ctaFields] }),
    defineField({ name: "trustBadges", title: "Trust Badges", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "associationTitle", title: "Association Column Title", type: "string" }),
    defineField({
      name: "associationCards",
      title: "Why Choose SRSGA Cards",
      type: "array",
      of: [{ type: "object", fields: [...titleDescriptionFields], preview: { select: { title: "title" } } }],
    }),
    defineField({ name: "treeValueTitle", title: "Tree Value Column Title", type: "string" }),
    defineField({
      name: "treeValueCards",
      title: "Why Grow These Trees Cards",
      type: "array",
      of: [{ type: "object", fields: [...titleDescriptionFields], preview: { select: { title: "title" } } }],
    }),
    defineField({ name: "comparisonTitle", title: "Comparison Section Title", type: "string" }),
    defineField({ name: "comparisonSubtitle", title: "Comparison Section Subtitle", type: "text", rows: 2 }),
    defineField({
      name: "comparisonCards",
      title: "Comparison Cards",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "badge", title: "Badge", type: "string" }),
            defineField({ name: "highlight", title: "Highlight", type: "string" }),
            defineField({ name: "description", title: "Description", type: "text", rows: 3 }),
            defineField({ name: "image", title: "Image", type: "image", options: { hotspot: true } }),
          ],
          preview: { select: { title: "title", subtitle: "badge", media: "image" } },
        },
      ],
    }),
    defineField({ name: "historyEyebrow", title: "History Eyebrow", type: "string" }),
    defineField({ name: "historyTitle", title: "History Title", type: "string" }),
    defineField({ name: "historyBody", title: "History Body", type: "blockContent" }),
    defineField({ name: "historyImage", title: "History Image", type: "image", options: { hotspot: true } }),
    defineField({
      name: "historyMilestones",
      title: "History Milestones",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "value", title: "Value", type: "string" }),
            defineField({ name: "label", title: "Label", type: "string" }),
            defineField({ name: "description", title: "Description", type: "text", rows: 2 }),
          ],
          preview: { select: { title: "label", subtitle: "value" } },
        },
      ],
    }),
    defineField({ name: "memberBenefitsTitle", title: "Member Benefits Title", type: "string" }),
    defineField({ name: "memberBenefitsSubtitle", title: "Member Benefits Subtitle", type: "text", rows: 2 }),
    defineField({
      name: "memberBenefits",
      title: "Member Benefits Cards",
      type: "array",
      of: [{ type: "object", fields: [...titleDescriptionFields], preview: { select: { title: "title" } } }],
    }),
    defineField({ name: "supportTitle", title: "Support Title", type: "string" }),
    defineField({ name: "supportSubtitle", title: "Support Subtitle", type: "text", rows: 2 }),
    defineField({ name: "supportItems", title: "Support Items", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "legalTitle", title: "Legal Advice Title", type: "string" }),
    defineField({ name: "legalSubtitle", title: "Legal Advice Subtitle", type: "text", rows: 2 }),
    defineField({ name: "legalItems", title: "Legal Advice Items", type: "array", of: [{ type: "string" }] }),
    defineField({ name: "journeyTitle", title: "Journey Title", type: "string" }),
    defineField({ name: "journeySubtitle", title: "Journey Subtitle", type: "text", rows: 2 }),
    defineField({
      name: "journeySteps",
      title: "Journey Steps",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "step", title: "Step Number", type: "string" }),
            defineField({ name: "title", title: "Title", type: "string" }),
            defineField({ name: "description", title: "Description", type: "text", rows: 3 }),
            defineField({ name: "image", title: "Image", type: "image", options: { hotspot: true } }),
          ],
          preview: { select: { title: "title", subtitle: "step", media: "image" } },
        },
      ],
    }),
    defineField({ name: "faqTitle", title: "FAQ Title", type: "string" }),
    defineField({ name: "faqSubtitle", title: "FAQ Subtitle", type: "text", rows: 2 }),
    defineField({
      name: "faqs",
      title: "FAQs",
      type: "array",
      of: [
        {
          type: "object",
          fields: [
            defineField({ name: "question", title: "Question", type: "string" }),
            defineField({ name: "answer", title: "Answer", type: "text", rows: 4 }),
          ],
          preview: { select: { title: "question" } },
        },
      ],
    }),
    defineField({ name: "ctaTitle", title: "Bottom CTA Title", type: "string" }),
    defineField({ name: "ctaSubtitle", title: "Bottom CTA Subtitle", type: "text", rows: 3 }),
    defineField({ name: "ctaTrustLine", title: "Bottom CTA Trust Line", type: "string" }),
    defineField({ name: "ctaPrimary", title: "Bottom CTA Primary", type: "object", fields: [...ctaFields] }),
    defineField({ name: "ctaSecondary", title: "Bottom CTA Secondary", type: "object", fields: [...ctaFields] }),
    defineField({ name: "seo", title: "SEO", type: "seoFields" }),
  ],
  initialValue: {
    heroLabel: "For farmers, landowners, and future growers",
    heroTitle: "Grow Sandalwood & Red Sandalwood with the Right Guidance",
    heroSubtitle:
      "SRSGA supports growers with guidance, member support, legal awareness, and practical help from planting to long-term growth.",
    heroPrimaryCta: { label: "Join SRSGA", href: "/join-now" },
    heroSecondaryCta: { label: "Explore Member Benefits", href: "/farmer-benefits" },
    trustBadges: ["Farmer Support", "Legal Guidance", "Member Network", "Long-Term Tree Value"],
    associationTitle: "Why Choose SRSGA",
    associationCards: [
      { title: "Trusted grower guidance", description: "Practical help instead of confusing information." },
      { title: "Support for members", description: "Association-led support across the grower journey." },
      { title: "Legal awareness", description: "Clarity around documentation and permissions." },
      { title: "Practical plantation help", description: "Useful support from planning to long-term growth." },
    ],
    treeValueTitle: "Why Grow Sandalwood & Red Sandalwood",
    treeValueCards: [
      { title: "High-value tree crops", description: "Premium long-term tree categories with strong relevance." },
      { title: "Long-term family asset", description: "A crop story linked with patient future planning." },
      { title: "Regional relevance", description: "Strong South India cultivation relevance and awareness." },
      { title: "Strong future demand story", description: "Long-term demand narrative matters to growers." },
    ],
    comparisonTitle: "Sandalwood vs Red Sandalwood",
    comparisonSubtitle: "A simple comparison helps users understand both topics quickly.",
    comparisonCards: [
      {
        title: "Sandalwood",
        badge: "Premium crop",
        highlight: "Aromatic • premium • long-term value",
        description: "Aromatic and premium, often associated with long-term value and careful cultivation.",
      },
      {
        title: "Red Sandalwood",
        badge: "Region-linked crop",
        highlight: "Rare • high-value • region-linked cultivation",
        description: "Rare and high-value, with strong regional relevance and legal awareness needs.",
      },
    ],
    historyEyebrow: "SRSGA history",
    historyTitle: "An association built around grower confidence, not sales pressure.",
    historyMilestones: [
      { value: "01", label: "Grower-led start", description: "Built around real grower needs." },
      { value: "02", label: "Support-focused approach", description: "Clarity and guidance come first." },
      { value: "03", label: "Long-term vision", description: "Helping members plan ahead." },
    ],
    memberBenefitsTitle: "Member Benefits",
    memberBenefitsSubtitle: "Show why membership matters without overloading the homepage.",
    memberBenefits: [
      { title: "Guidance", description: "Clear support for growers." },
      { title: "Plantation support", description: "Better planning and progress." },
      { title: "Member community", description: "Grow with a trusted network." },
      { title: "Legal awareness", description: "Understand key legal directions." },
      { title: "Updates & learning", description: "Stay informed over time." },
      { title: "Help with next steps", description: "Move ahead with confidence." },
    ],
    supportTitle: "Support",
    supportSubtitle: "Practical help for growers who need clarity and direction.",
    supportItems: ["Basic grower guidance", "Plantation planning support", "Member helpdesk direction", "Support for new growers"],
    legalTitle: "Legal Advice",
    legalSubtitle: "Awareness-focused guidance around permissions and documentation.",
    legalItems: ["Documentation awareness", "Permissions guidance", "Compliance direction", "Right next steps"],
    journeyTitle: "How It Works / Journey to Grow",
    journeySubtitle: "A clear process gives confidence to first-time growers.",
    journeySteps: [
      { step: "01", title: "Understand the crop", description: "Know the value and relevance first." },
      { step: "02", title: "Prepare land", description: "Plan the land and growing setup." },
      { step: "03", title: "Get proper planting guidance", description: "Move forward with practical support." },
      { step: "04", title: "Maintain and monitor", description: "Care for the crop over time." },
      { step: "05", title: "Grow with long-term planning", description: "Think ahead with support and awareness." },
    ],
    faqTitle: "Frequently asked questions",
    faqSubtitle: "Use FAQ to reduce hesitation and build trust.",
    faqs: [
      { question: "Is it legal to grow sandalwood or red sandalwood?", answer: "Growers need the right awareness and legal guidance before acting." },
      { question: "Who can join SRSGA?", answer: "Farmers, landowners, and future growers looking for trusted support." },
      { question: "Does SRSGA support new growers?", answer: "Yes. New growers can get guidance and clarity." },
      { question: "What kind of land is suitable?", answer: "Land suitability depends on the crop and planning context." },
      { question: "Why should I become a member?", answer: "Membership helps with support, awareness, and a more guided path." },
    ],
    ctaTitle: "Build your future with better guidance, not confusion.",
    ctaSubtitle: "Join SRSGA to explore member support, legal awareness, and practical help for growers.",
    ctaTrustLine: "Trusted guidance for growers who want clarity, support, and a long-term view.",
    ctaPrimary: { label: "Join SRSGA", href: "/join-now" },
    ctaSecondary: { label: "Contact Us", href: "/contact" },
  },
  preview: { select: { title: "heroTitle" } },
});
